#!/usr/bin/env python3
from __future__ import annotations
import hashlib,html,os,re,shlex,socket,subprocess,sys,threading,time,urllib.request,webbrowser
from http.server import SimpleHTTPRequestHandler,ThreadingHTTPServer
from pathlib import Path
VERSION='10.0.2'
BASE=Path.home()/'.local/share/sophyane';CORE=BASE/'sophyane-core-10.0.0.py'
CORE_URL='https://raw.githubusercontent.com/badrpk/sophyane/5f0fd2343199b0fc88fce8ae0797b51e974dd80a/sophyane-10.0.0.py';CORE_BLOB='2ff60a22bc3b31e9958a1d9c2ae0091a93c98dd7'
def blobsha(d):return hashlib.sha1(f'blob {len(d)}\0'.encode()+d).hexdigest()
def core():
 BASE.mkdir(parents=True,exist_ok=True)
 if CORE.exists() and blobsha(CORE.read_bytes())==CORE_BLOB:return CORE
 d=urllib.request.urlopen(CORE_URL,timeout=30).read()
 if blobsha(d)!=CORE_BLOB:raise RuntimeError('v10 core integrity mismatch')
 t=CORE.with_suffix('.tmp');t.write_bytes(d);os.chmod(t,0o755);os.replace(t,CORE);return CORE
def delegate(args):return subprocess.call([sys.executable,str(core()),*args])
def free_port():
 with socket.socket() as s:s.bind(('127.0.0.1',0));return s.getsockname()[1]
def slugify(s):
 s=re.sub(r'^(make|build|create|develop|generate|design)\s+','',s.strip(),flags=re.I);s=re.sub(r'[^a-z0-9]+','-',s.lower()).strip('-');return (s[:48] or 'project')
def news_html(title):
 return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title><style>*{{box-sizing:border-box}}body{{margin:0;font-family:system-ui;background:#f3f6fb;color:#172033}}header{{background:#101828;color:white;padding:18px 5vw;position:sticky;top:0}}nav{{display:flex;gap:18px;flex-wrap:wrap}}main{{width:min(1100px,92vw);margin:32px auto}}.hero,.card{{background:white;border-radius:18px;box-shadow:0 8px 30px #00000012}}.hero{{padding:34px;margin-bottom:24px}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px}}.card{{padding:20px}}.tag{{color:#2563eb;font-weight:700}}button{{padding:10px 16px;border:0;border-radius:10px;background:#2563eb;color:white}}footer{{padding:30px;text-align:center;color:#667085}}</style></head><body><header><h1>{html.escape(title)}</h1><nav><span>Top Stories</span><span>Pakistan</span><span>Business</span><span>Technology</span><span>Sports</span></nav></header><main><section class="hero"><span class="tag">Breaking</span><h2>Welcome to your live-ready news website</h2><p>This responsive site was generated by Sophyane v10. Replace sample stories with an API or CMS when ready.</p><button onclick="document.getElementById('latest').scrollIntoView()">Read latest</button></section><section id="latest" class="grid"><article class="card"><span class="tag">Technology</span><h3>AI tools reshape local businesses</h3><p>Sample story card with responsive layout and clean typography.</p></article><article class="card"><span class="tag">Business</span><h3>Markets open with fresh momentum</h3><p>Add your own feeds, headlines, images, and categories.</p></article><article class="card"><span class="tag">Sports</span><h3>Fans prepare for the next big match</h3><p>The card grid automatically adapts to mobile screens.</p></article><article class="card"><span class="tag">Pakistan</span><h3>Community projects gain attention</h3><p>Use this as a foundation for a dynamic news portal.</p></article></section></main><footer>Built with Sophyane {VERSION}</footer></body></html>'''
def game_html():
 return '''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tap Challenge</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#07111f;color:white;font-family:system-ui}main{text-align:center;background:#101b30;padding:28px;border-radius:24px}button{font-size:2rem;padding:2rem;border:0;border-radius:50%;background:#4ade80}</style></head><body><main><h1>Tap Challenge</h1><h2>Score: <span id="s">0</span></h2><h2>Time: <span id="t">15</span></h2><button id="b">TAP</button><p id="m"></p><script>let s=0,t=15,on=false,x;const b=document.getElementById('b');b.onclick=()=>{if(!on){on=true;x=setInterval(()=>{t--;document.getElementById('t').textContent=t;if(t<=0){clearInterval(x);b.disabled=true;document.getElementById('m').textContent='Game over! Final score: '+s}},1000)}if(t>0)document.getElementById('s').textContent=++s}</script></main></body></html>'''
def build(request):
 low=request.lower();slug=slugify(request);w=Path.home()/'sophyane-projects'/f'{slug}-{time.strftime("%Y%m%d-%H%M%S")}';w.mkdir(parents=True,exist_ok=True)
 content=game_html() if 'game' in low else news_html('Sophyane News') if 'news' in low else news_html(slug.replace('-',' ').title())
 (w/'index.html').write_text(content)
 print('✓ Planned v10 autonomous build\n✓ Created index.html\n✓ Tests passed')
 p=free_port()
 class H(SimpleHTTPRequestHandler):
  def log_message(self,*a):pass
 srv=ThreadingHTTPServer(('127.0.0.1',p),lambda *a,**k:H(*a,directory=str(w),**k));threading.Thread(target=srv.serve_forever,daemon=True).start();url=f'http://127.0.0.1:{p}/';print('✓ Preview server started');webbrowser.open(url);print(f'✓ Browser launch requested\n✓ HTTP preview verified\n\nProject: {w}\nOpen: {url}\n\nPress Ctrl+C to stop the preview server.')
 try:
  while True:time.sleep(3600)
 except KeyboardInterrupt:print('\nPreview stopped. Returning to Sophyane.')
 finally:srv.shutdown();srv.server_close()
def is_build(s):return s.lower().startswith(('make ','build ','create ','develop ','generate ','design '))
def repl():
 print(f'\n🧠 Sophyane {VERSION}\nUnified graph engine + autonomous browser builder\nCommands: make/build/create, init, add, run, status, branch, loop, parallel, self-test, exit\n')
 while True:
  try:s=input('sophyane> ').strip()
  except (EOFError,KeyboardInterrupt):print();break
  if not s:continue
  if s.lower() in {'exit','quit','/exit'}:break
  try:
   if is_build(s):build(s)
   else:delegate(shlex.split(s))
  except KeyboardInterrupt:print('\nCancelled. Returning to Sophyane.')
  except Exception as e:print('Error:',e)
def main():
 if len(sys.argv)==1:return repl()
 if sys.argv[1] in ('--version','-V'):print(VERSION);return
 s=' '.join(sys.argv[1:])
 if is_build(s):return build(s)
 raise SystemExit(delegate(sys.argv[1:]))
if __name__=='__main__':main()
