"""PostgreSQL backend for Sophyane Learning Intelligence.

This module intentionally does not change the default SLI runtime yet.
It provides a production-ready backend whose behavior can be compared
against the existing SQLite implementation before cutover.
"""
from __future__ import annotations

import json
import math
import os
import time
from typing import Any

import psycopg
from psycopg import sql
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb


SOURCE_WEIGHTS = {
    "execution": 1.00,
    "validator": 0.95,
    "user_feedback": 0.90,
    "manual": 0.80,
    "seed": 0.60,
    "unknown": 0.35,
    "scanned_log": 0.15,
    "synthetic": 0.10,
}


def _tokens(
    value: object,
) -> set[str]:
    return {
        token
        for token in "".join(
            character.lower()
            if character.isalnum()
            else " "
            for character in str(
                value
                or ""
            )
        ).split()
        if len(
            token
        ) > 1
    }


def _similarity(
    left: object,
    right: object,
) -> float:
    a = _tokens(
        left
    )

    b = _tokens(
        right
    )

    if not a or not b:
        return 0.0

    return (
        len(
            a
            & b
        )
        / math.sqrt(
            len(
                a
            )
            * len(
                b
            )
        )
    )


class PostgresSLIStore:
    def __init__(
        self,
        dsn: str | None = None,
        *,
        schema: str = "sli",
    ) -> None:
        self.dsn = (
            str(
                dsn
                or os.environ.get(
                    "SOPHYANE_POSTGRES_DSN",
                    "",
                )
            ).strip()
        )

        if not self.dsn:
            raise RuntimeError(
                "SOPHYANE_POSTGRES_DSN is required "
                "for PostgreSQL SLI."
            )

        self.schema = (
            str(
                schema
            ).strip()
            or "sli"
        )

    def connect(
        self,
    ):
        return psycopg.connect(
            self.dsn,
            row_factory=dict_row,
            connect_timeout=3,
        )

    def ensure_schema(
        self,
    ) -> None:
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        "CREATE SCHEMA IF NOT EXISTS {}"
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                cursor.execute(
                    sql.SQL(
                        """
                        CREATE TABLE IF NOT EXISTS {}.memories (
                            id BIGINT GENERATED BY DEFAULT
                                AS IDENTITY PRIMARY KEY,
                            request TEXT NOT NULL,
                            state TEXT NOT NULL DEFAULT '',
                            action TEXT NOT NULL,
                            result TEXT NOT NULL DEFAULT '',
                            reward DOUBLE PRECISION NOT NULL
                                DEFAULT 0,
                            confidence DOUBLE PRECISION NOT NULL
                                DEFAULT 0.5,
                            elapsed_seconds DOUBLE PRECISION NOT NULL
                                DEFAULT 0,
                            source_type TEXT NOT NULL
                                DEFAULT 'unknown',
                            created_at DOUBLE PRECISION NOT NULL
                        )
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                cursor.execute(
                    sql.SQL(
                        """
                        CREATE INDEX IF NOT EXISTS
                        memories_action_idx
                        ON {}.memories(action)
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                cursor.execute(
                    sql.SQL(
                        """
                        CREATE INDEX IF NOT EXISTS
                        memories_source_type_idx
                        ON {}.memories(source_type)
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                cursor.execute(
                    sql.SQL(
                        """
                        CREATE TABLE IF NOT EXISTS
                        {}.learned_execution_traces (
                            trace_id TEXT PRIMARY KEY,
                            request TEXT NOT NULL,
                            action TEXT NOT NULL,
                            status TEXT NOT NULL,
                            reward DOUBLE PRECISION NOT NULL,
                            quality_reward DOUBLE PRECISION NOT NULL
                                DEFAULT 0,
                            failure_category TEXT NOT NULL
                                DEFAULT '',
                            quality_signals JSONB NOT NULL
                                DEFAULT '[]'::jsonb,
                            result TEXT NOT NULL DEFAULT '',
                            elapsed_seconds DOUBLE PRECISION NOT NULL
                                DEFAULT 0,
                            workspace_before JSONB NOT NULL
                                DEFAULT '{{}}'::jsonb,
                            workspace_after JSONB NOT NULL
                                DEFAULT '{{}}'::jsonb,
                            created_at DOUBLE PRECISION NOT NULL
                        )
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

            connection.commit()

    def record(
        self,
        *,
        request: str,
        action: str,
        reward: float,
        state: str = "",
        result: str = "",
        confidence: float = 0.5,
        elapsed_seconds: float = 0.0,
        source_type: str = "unknown",
    ) -> int:
        source = (
            source_type
            if source_type
            in SOURCE_WEIGHTS
            else "unknown"
        )

        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        INSERT INTO {}.memories (
                            request,
                            state,
                            action,
                            result,
                            reward,
                            confidence,
                            elapsed_seconds,
                            source_type,
                            created_at
                        )
                        VALUES (
                            %s, %s, %s, %s, %s,
                            %s, %s, %s, %s
                        )
                        RETURNING id
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        str(
                            request
                        ),
                        str(
                            state
                        ),
                        str(
                            action
                        ),
                        str(
                            result
                        ),
                        max(
                            -1.0,
                            min(
                                1.0,
                                float(
                                    reward
                                ),
                            ),
                        ),
                        max(
                            0.0,
                            min(
                                1.0,
                                float(
                                    confidence
                                ),
                            ),
                        ),
                        max(
                            0.0,
                            float(
                                elapsed_seconds
                            ),
                        ),
                        source,
                        time.time(),
                    ),
                )

                row = cursor.fetchone()

            connection.commit()

        if not row:
            raise RuntimeError(
                "PostgreSQL SLI record insert "
                "returned no id."
            )

        return int(
            row[
                "id"
            ]
        )

    def recommend_actions(
        self,
        *,
        request: str,
        state: str = "",
        limit: int = 5,
    ) -> list[dict[str, Any]]:
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            id,
                            request,
                            state,
                            action,
                            result,
                            reward,
                            confidence,
                            elapsed_seconds,
                            source_type,
                            created_at
                        FROM {}.memories
                        ORDER BY created_at DESC
                        LIMIT 2000
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                rows = cursor.fetchall()

        by_action: dict[
            str,
            list[
                tuple[
                    float,
                    dict[str, Any],
                ]
            ],
        ] = {}

        query = (
            f"{request} {state}"
        ).strip()

        for row in rows:
            similarity = _similarity(
                query,
                (
                    f"{row['request']} "
                    f"{row['state']}"
                ),
            )

            source_weight = SOURCE_WEIGHTS.get(
                str(
                    row[
                        "source_type"
                    ]
                ),
                0.35,
            )

            reward_factor = (
                float(
                    row[
                        "reward"
                    ]
                )
                + 1.0
            ) / 2.0

            confidence = float(
                row[
                    "confidence"
                ]
            )

            recency = (
                1.0
                / (
                    1.0
                    + max(
                        0.0,
                        time.time()
                        - float(
                            row[
                                "created_at"
                            ]
                        ),
                    )
                    / 86400.0
                )
            )

            score = (
                source_weight
                * (
                    0.50
                    * similarity
                    + 0.25
                    * reward_factor
                    + 0.15
                    * confidence
                    + 0.10
                    * recency
                )
            )

            by_action.setdefault(
                str(
                    row[
                        "action"
                    ]
                ),
                [],
            ).append(
                (
                    score,
                    row,
                )
            )

        ranked: list[
            dict[str, Any]
        ] = []

        for action, examples in by_action.items():
            examples.sort(
                key=lambda item: item[
                    0
                ],
                reverse=True,
            )

            strongest = examples[
                :3
            ]

            confidence = (
                sum(
                    item[
                        0
                    ]
                    for item in strongest
                )
                / len(
                    strongest
                )
            )

            best = strongest[
                0
            ][
                1
            ]

            ranked.append(
                {
                    "action":
                        action,

                    "confidence":
                        confidence,

                    "best_example":
                        str(
                            best[
                                "request"
                            ]
                        ),

                    "best_source":
                        str(
                            best[
                                "source_type"
                            ]
                        ),

                    "attempts":
                        len(
                            examples
                        ),
                }
            )

        ranked.sort(
            key=lambda item: item[
                "confidence"
            ],
            reverse=True,
        )

        return ranked[
            : max(
                1,
                int(
                    limit
                ),
            )
        ]

    def stats(
        self,
    ) -> dict[str, Any]:
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            COUNT(*) AS attempts,
                            COUNT(DISTINCT action)
                                AS actions,
                            SUM(
                                CASE
                                    WHEN reward > 0
                                    THEN 1
                                    ELSE 0
                                END
                            ) AS positive,
                            SUM(
                                CASE
                                    WHEN reward < 0
                                    THEN 1
                                    ELSE 0
                                END
                            ) AS negative,
                            COALESCE(
                                AVG(reward),
                                0
                            ) AS average_reward,
                            COALESCE(
                                AVG(elapsed_seconds),
                                0
                            ) AS average_elapsed
                        FROM {}.memories
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                aggregate = cursor.fetchone()

                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            source_type,
                            COUNT(*) AS n
                        FROM {}.memories
                        GROUP BY source_type
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                source_rows = cursor.fetchall()

        aggregate = aggregate or {
            "attempts": 0,
            "actions": 0,
            "positive": 0,
            "negative": 0,
            "average_reward": 0,
            "average_elapsed": 0,
        }

        sources = {
            str(
                row[
                    "source_type"
                ]
            ):
            int(
                row[
                    "n"
                ]
            )
            for row in source_rows
        }

        return {
            "database":
                "postgresql:sophyane/"
                + self.schema,

            "learned_executions":
                int(
                    aggregate[
                        "attempts"
                    ]
                    or 0
                ),

            "distinct_actions":
                int(
                    aggregate[
                        "actions"
                    ]
                    or 0
                ),

            "positive_outcomes":
                int(
                    aggregate[
                        "positive"
                    ]
                    or 0
                ),

            "negative_outcomes":
                int(
                    aggregate[
                        "negative"
                    ]
                    or 0
                ),

            "average_reward":
                float(
                    aggregate[
                        "average_reward"
                    ]
                    or 0
                ),

            "average_elapsed":
                float(
                    aggregate[
                        "average_elapsed"
                    ]
                    or 0
                ),

            "sources":
                sources,
        }

    def store_trace(
        self,
        payload: dict[str, Any],
    ) -> None:
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        INSERT INTO
                        {}.learned_execution_traces (
                            trace_id,
                            request,
                            action,
                            status,
                            reward,
                            quality_reward,
                            failure_category,
                            quality_signals,
                            result,
                            elapsed_seconds,
                            workspace_before,
                            workspace_after,
                            created_at
                        )
                        VALUES (
                            %s, %s, %s, %s, %s,
                            %s, %s, %s, %s, %s,
                            %s, %s, %s
                        )
                        ON CONFLICT (trace_id)
                        DO UPDATE SET
                            request =
                                EXCLUDED.request,
                            action =
                                EXCLUDED.action,
                            status =
                                EXCLUDED.status,
                            reward =
                                EXCLUDED.reward,
                            quality_reward =
                                EXCLUDED.quality_reward,
                            failure_category =
                                EXCLUDED.failure_category,
                            quality_signals =
                                EXCLUDED.quality_signals,
                            result =
                                EXCLUDED.result,
                            elapsed_seconds =
                                EXCLUDED.elapsed_seconds,
                            workspace_before =
                                EXCLUDED.workspace_before,
                            workspace_after =
                                EXCLUDED.workspace_after,
                            created_at =
                                EXCLUDED.created_at
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        str(
                            payload.get(
                                "trace_id"
                            )
                            or ""
                        ),
                        str(
                            payload.get(
                                "request"
                            )
                            or ""
                        ),
                        str(
                            payload.get(
                                "action"
                            )
                            or
                            "EXECUTE_STRUCTURED_TASK"
                        ),
                        str(
                            payload.get(
                                "status"
                            )
                            or "unknown"
                        ),
                        float(
                            payload.get(
                                "reward"
                            )
                            or 0.0
                        ),
                        float(
                            payload.get(
                                "quality_reward"
                            )
                            or 0.0
                        ),
                        str(
                            payload.get(
                                "failure_category"
                            )
                            or ""
                        ),
                        Jsonb(
                            payload.get(
                                "quality_signals"
                            )
                            or []
                        ),
                        str(
                            payload.get(
                                "result"
                            )
                            or ""
                        ),
                        float(
                            payload.get(
                                "elapsed_seconds"
                            )
                            or 0.0
                        ),
                        Jsonb(
                            payload.get(
                                "workspace_before"
                            )
                            or {}
                        ),
                        Jsonb(
                            payload.get(
                                "workspace_after"
                            )
                            or {}
                        ),
                        time.time(),
                    ),
                )

            connection.commit()

    def list_traces(
        self,
        *,
        limit: int = 10,
    ) -> list[dict[str, Any]]:
        count = max(
            1,
            int(
                limit
            ),
        )

        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            trace_id,
                            request,
                            action,
                            status,
                            reward,
                            quality_reward,
                            failure_category,
                            quality_signals,
                            result,
                            elapsed_seconds,
                            workspace_before,
                            workspace_after,
                            created_at
                        FROM {}.learned_execution_traces
                        ORDER BY created_at DESC
                        LIMIT %s
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        count,
                    ),
                )

                rows = cursor.fetchall()

        return [
            dict(
                row
            )
            for row in rows
        ]
