"""PostgreSQL backend for Sophyane Learning Intelligence.

This module intentionally does not change the default SLI runtime yet.
It provides a production-ready backend whose behavior can be compared
against the existing SQLite implementation before cutover.
"""
from __future__ import annotations

import json
import math
import os
import time
from typing import Any

import psycopg
from psycopg import sql
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb


SOURCE_WEIGHTS = {
    "execution": 1.00,
    "validator": 0.95,
    "user_feedback": 0.90,
    "manual": 0.80,
    "seed": 0.60,
    "unknown": 0.35,
    "scanned_log": 0.15,
    "synthetic": 0.10,
}


def _tokens(
    value: object,
) -> set[str]:
    return {
        token
        for token in "".join(
            character.lower()
            if character.isalnum()
            else " "
            for character in str(
                value
                or ""
            )
        ).split()
        if len(
            token
        ) > 1
    }


def _similarity(
    left: object,
    right: object,
) -> float:
    a = _tokens(
        left
    )

    b = _tokens(
        right
    )

    if not a or not b:
        return 0.0

    return (
        len(
            a
            & b
        )
        / math.sqrt(
            len(
                a
            )
            * len(
                b
            )
        )
    )


class PostgresSLIStore:
    def __init__(
        self,
        dsn: str | None = None,
        *,
        schema: str = "sli",
    ) -> None:
        self.dsn = (
            str(
                dsn
                or os.environ.get(
                    "SOPHYANE_POSTGRES_DSN",
                    "",
                )
            ).strip()
        )

        if not self.dsn:
            raise RuntimeError(
                "SOPHYANE_POSTGRES_DSN is required "
                "for PostgreSQL SLI."
            )

        self.schema = (
            str(
                schema
            ).strip()
            or "sli"
        )

    def connect(
        self,
    ):
        return psycopg.connect(
            self.dsn,
            row_factory=dict_row,
            connect_timeout=3,
        )

    def ensure_schema(
        self,
    ) -> None:
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        "CREATE SCHEMA IF NOT EXISTS {}"
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                cursor.execute(
                    sql.SQL(
                        """
                        CREATE TABLE IF NOT EXISTS {}.memories (
                            id BIGINT GENERATED BY DEFAULT
                                AS IDENTITY PRIMARY KEY,
                            request TEXT NOT NULL,
                            state TEXT NOT NULL DEFAULT '',
                            action TEXT NOT NULL,
                            result TEXT NOT NULL DEFAULT '',
                            reward DOUBLE PRECISION NOT NULL
                                DEFAULT 0,
                            confidence DOUBLE PRECISION NOT NULL
                                DEFAULT 0.5,
                            elapsed_seconds DOUBLE PRECISION NOT NULL
                                DEFAULT 0,
                            source_type TEXT NOT NULL
                                DEFAULT 'unknown',
                            created_at DOUBLE PRECISION NOT NULL
                        )
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                cursor.execute(
                    sql.SQL(
                        """
                        CREATE INDEX IF NOT EXISTS
                        memories_action_idx
                        ON {}.memories(action)
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                cursor.execute(
                    sql.SQL(
                        """
                        CREATE INDEX IF NOT EXISTS
                        memories_source_type_idx
                        ON {}.memories(source_type)
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                cursor.execute(
                    sql.SQL(
                        """
                        CREATE TABLE IF NOT EXISTS
                        {}.learned_execution_traces (
                            trace_id TEXT PRIMARY KEY,
                            request TEXT NOT NULL,
                            action TEXT NOT NULL,
                            status TEXT NOT NULL,
                            reward DOUBLE PRECISION NOT NULL,
                            quality_reward DOUBLE PRECISION NOT NULL
                                DEFAULT 0,
                            failure_category TEXT NOT NULL
                                DEFAULT '',
                            quality_signals JSONB NOT NULL
                                DEFAULT '[]'::jsonb,
                            result TEXT NOT NULL DEFAULT '',
                            elapsed_seconds DOUBLE PRECISION NOT NULL
                                DEFAULT 0,
                            workspace_before JSONB NOT NULL
                                DEFAULT '{{}}'::jsonb,
                            workspace_after JSONB NOT NULL
                                DEFAULT '{{}}'::jsonb,
                            created_at DOUBLE PRECISION NOT NULL
                        )
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

            connection.commit()

    def ensure_learner_event_keys_schema(
        self,
    ) -> None:
        """Create the opt-in learner-event idempotency ledger.

        This is deliberately separate from ensure_schema(). Existing
        production installations must not acquire the new table merely
        by opening the normal PostgreSQL SLI backend.
        """
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        CREATE TABLE IF NOT EXISTS
                        {}.learner_event_keys (
                            trace_id TEXT PRIMARY KEY,
                            memory_id BIGINT UNIQUE NOT NULL,
                            payload_digest TEXT NOT NULL,
                            created_at DOUBLE PRECISION NOT NULL,

                            CONSTRAINT learner_event_keys_memory_fk
                            FOREIGN KEY (memory_id)
                            REFERENCES {}.memories(id)
                            ON DELETE RESTRICT
                        )
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        ),
                        sql.Identifier(
                            self.schema
                        ),
                    )
                )

            connection.commit()

    def get_learner_event_key(
        self,
        trace_id: str,
    ) -> dict[str, Any] | None:
        value = str(
            trace_id
        ).strip()

        if not value:
            raise ValueError(
                "trace_id must not be empty."
            )

        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            trace_id,
                            memory_id,
                            payload_digest,
                            created_at
                        FROM {}.learner_event_keys
                        WHERE trace_id = %s
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        value,
                    ),
                )

                row = cursor.fetchone()

        if row is None:
            return None

        return {
            "trace_id":
                str(
                    row[
                        "trace_id"
                    ]
                ),

            "memory_id":
                int(
                    row[
                        "memory_id"
                    ]
                ),

            "payload_digest":
                str(
                    row[
                        "payload_digest"
                    ]
                ),

            "created_at":
                float(
                    row[
                        "created_at"
                    ]
                ),
        }

    def atomic_learn_execution(
        self,
        *,
        trace_id: str,
        payload_digest: str,
        memory: dict[str, Any],
        trace: dict[str, Any],
    ) -> dict[str, Any]:
        """Atomically persist one authoritative learner event.

        The caller must explicitly create learner_event_keys first.
        Existing schemas therefore remain untouched until migration
        activation is deliberately performed.

        Same trace_id + same payload returns the original memory without
        modifying memories or traces. Same trace_id + a different payload
        fails closed.
        """
        trace_value = str(
            trace_id
        ).strip()

        digest_value = str(
            payload_digest
        ).strip()

        if not trace_value:
            raise ValueError(
                "trace_id must not be empty."
            )

        if not digest_value:
            raise ValueError(
                "payload_digest must not be empty."
            )

        trace_payload_id = str(
            trace.get(
                "trace_id",
                trace_value,
            )
            or ""
        ).strip()

        if trace_payload_id != trace_value:
            raise ValueError(
                "trace payload trace_id does not "
                "match authoritative trace_id."
            )

        source_type = str(
            memory.get(
                "source_type",
                "unknown",
            )
            or "unknown"
        )

        source = (
            source_type
            if source_type in SOURCE_WEIGHTS
            else "unknown"
        )

        memory_created_at_raw = (
            memory.get(
                "created_at"
            )
        )

        memory_created_at = (
            time.time()
            if memory_created_at_raw is None
            else float(
                memory_created_at_raw
            )
        )

        trace_created_at_raw = (
            trace.get(
                "created_at"
            )
        )

        trace_created_at = (
            time.time()
            if trace_created_at_raw is None
            else float(
                trace_created_at_raw
            )
        )

        with self.connect() as connection:
            with connection.cursor() as cursor:
                # Serialize concurrent contenders for one logical event
                # without globally serializing unrelated learning.
                cursor.execute(
                    """
                    SELECT pg_advisory_xact_lock(
                        hashtextextended(%s, 0)
                    )
                    """,
                    (
                        trace_value,
                    ),
                )

                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            memory_id,
                            payload_digest
                        FROM {}.learner_event_keys
                        WHERE trace_id = %s
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        trace_value,
                    ),
                )

                existing = (
                    cursor.fetchone()
                )

                if existing is not None:
                    existing_digest = str(
                        existing[
                            "payload_digest"
                        ]
                    )

                    memory_id = int(
                        existing[
                            "memory_id"
                        ]
                    )

                    if (
                        existing_digest
                        != digest_value
                    ):
                        raise RuntimeError(
                            "PostgreSQL SLI learner-event "
                            "payload conflict for trace_id "
                            f"{trace_value!r}."
                        )

                    return {
                        "state":
                            "already_recorded",

                        "trace_id":
                            trace_value,

                        "memory_id":
                            memory_id,

                        "payload_digest":
                            existing_digest,

                        "created":
                            False,
                    }

                cursor.execute(
                    sql.SQL(
                        """
                        INSERT INTO {}.memories (
                            request,
                            state,
                            action,
                            result,
                            reward,
                            confidence,
                            elapsed_seconds,
                            source_type,
                            created_at
                        )
                        VALUES (
                            %s, %s, %s, %s, %s,
                            %s, %s, %s, %s
                        )
                        RETURNING id
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        str(
                            memory.get(
                                "request"
                            )
                            or ""
                        ),
                        str(
                            memory.get(
                                "state"
                            )
                            or ""
                        ),
                        str(
                            memory.get(
                                "action"
                            )
                            or
                            "EXECUTE_STRUCTURED_TASK"
                        ),
                        str(
                            memory.get(
                                "result"
                            )
                            or ""
                        ),
                        max(
                            -1.0,
                            min(
                                1.0,
                                float(
                                    memory.get(
                                        "reward",
                                        0.0,
                                    )
                                ),
                            ),
                        ),
                        max(
                            0.0,
                            min(
                                1.0,
                                float(
                                    memory.get(
                                        "confidence",
                                        0.5,
                                    )
                                ),
                            ),
                        ),
                        max(
                            0.0,
                            float(
                                memory.get(
                                    "elapsed_seconds",
                                    0.0,
                                )
                            ),
                        ),
                        source,
                        memory_created_at,
                    ),
                )

                memory_row = (
                    cursor.fetchone()
                )

                if not memory_row:
                    raise RuntimeError(
                        "Atomic PostgreSQL learner "
                        "memory insert returned no id."
                    )

                memory_id = int(
                    memory_row[
                        "id"
                    ]
                )

                # Intentionally plain INSERT: a retry must never mutate
                # historical trace content.
                cursor.execute(
                    sql.SQL(
                        """
                        INSERT INTO
                        {}.learned_execution_traces (
                            trace_id,
                            request,
                            action,
                            status,
                            reward,
                            quality_reward,
                            failure_category,
                            quality_signals,
                            result,
                            elapsed_seconds,
                            workspace_before,
                            workspace_after,
                            created_at
                        )
                        VALUES (
                            %s, %s, %s, %s, %s,
                            %s, %s, %s, %s, %s,
                            %s, %s, %s
                        )
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        trace_value,
                        str(
                            trace.get(
                                "request"
                            )
                            or ""
                        ),
                        str(
                            trace.get(
                                "action"
                            )
                            or
                            "EXECUTE_STRUCTURED_TASK"
                        ),
                        str(
                            trace.get(
                                "status"
                            )
                            or "unknown"
                        ),
                        float(
                            trace.get(
                                "reward",
                                0.0,
                            )
                        ),
                        float(
                            trace.get(
                                "quality_reward",
                                0.0,
                            )
                        ),
                        str(
                            trace.get(
                                "failure_category"
                            )
                            or ""
                        ),
                        Jsonb(
                            trace.get(
                                "quality_signals",
                                [],
                            )
                            or []
                        ),
                        str(
                            trace.get(
                                "result"
                            )
                            or ""
                        ),
                        max(
                            0.0,
                            float(
                                trace.get(
                                    "elapsed_seconds",
                                    0.0,
                                )
                            ),
                        ),
                        Jsonb(
                            trace.get(
                                "workspace_before",
                                {},
                            )
                            or {}
                        ),
                        Jsonb(
                            trace.get(
                                "workspace_after",
                                {},
                            )
                            or {}
                        ),
                        trace_created_at,
                    ),
                )

                cursor.execute(
                    sql.SQL(
                        """
                        INSERT INTO
                        {}.learner_event_keys (
                            trace_id,
                            memory_id,
                            payload_digest,
                            created_at
                        )
                        VALUES (
                            %s, %s, %s, %s
                        )
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        trace_value,
                        memory_id,
                        digest_value,
                        time.time(),
                    ),
                )

            # memory + immutable trace + event key become
            # authoritative together.
            connection.commit()

        return {
            "state":
                "created",

            "trace_id":
                trace_value,

            "memory_id":
                memory_id,

            "payload_digest":
                digest_value,

            "created":
                True,
        }

    def record(
        self,
        *,
        request: str,
        action: str,
        reward: float,
        state: str = "",
        result: str = "",
        confidence: float = 0.5,
        elapsed_seconds: float = 0.0,
        source_type: str = "unknown",
    ) -> int:
        source = (
            source_type
            if source_type
            in SOURCE_WEIGHTS
            else "unknown"
        )

        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        INSERT INTO {}.memories (
                            request,
                            state,
                            action,
                            result,
                            reward,
                            confidence,
                            elapsed_seconds,
                            source_type,
                            created_at
                        )
                        VALUES (
                            %s, %s, %s, %s, %s,
                            %s, %s, %s, %s
                        )
                        RETURNING id
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        str(
                            request
                        ),
                        str(
                            state
                        ),
                        str(
                            action
                        ),
                        str(
                            result
                        ),
                        max(
                            -1.0,
                            min(
                                1.0,
                                float(
                                    reward
                                ),
                            ),
                        ),
                        max(
                            0.0,
                            min(
                                1.0,
                                float(
                                    confidence
                                ),
                            ),
                        ),
                        max(
                            0.0,
                            float(
                                elapsed_seconds
                            ),
                        ),
                        source,
                        time.time(),
                    ),
                )

                row = cursor.fetchone()

            connection.commit()

        if not row:
            raise RuntimeError(
                "PostgreSQL SLI record insert "
                "returned no id."
            )

        return int(
            row[
                "id"
            ]
        )

    def recommend_actions(
        self,
        *,
        request: str,
        state: str = "",
        limit: int = 5,
    ) -> list[dict[str, Any]]:
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            id,
                            request,
                            state,
                            action,
                            result,
                            reward,
                            confidence,
                            elapsed_seconds,
                            source_type,
                            created_at
                        FROM {}.memories
                        ORDER BY created_at DESC
                        LIMIT 2000
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                rows = cursor.fetchall()

        by_action: dict[
            str,
            list[
                tuple[
                    float,
                    dict[str, Any],
                ]
            ],
        ] = {}

        query = (
            f"{request} {state}"
        ).strip()

        for row in rows:
            similarity = _similarity(
                query,
                (
                    f"{row['request']} "
                    f"{row['state']}"
                ),
            )

            source_weight = SOURCE_WEIGHTS.get(
                str(
                    row[
                        "source_type"
                    ]
                ),
                0.35,
            )

            reward_factor = (
                float(
                    row[
                        "reward"
                    ]
                )
                + 1.0
            ) / 2.0

            confidence = float(
                row[
                    "confidence"
                ]
            )

            recency = (
                1.0
                / (
                    1.0
                    + max(
                        0.0,
                        time.time()
                        - float(
                            row[
                                "created_at"
                            ]
                        ),
                    )
                    / 86400.0
                )
            )

            score = (
                source_weight
                * (
                    0.50
                    * similarity
                    + 0.25
                    * reward_factor
                    + 0.15
                    * confidence
                    + 0.10
                    * recency
                )
            )

            by_action.setdefault(
                str(
                    row[
                        "action"
                    ]
                ),
                [],
            ).append(
                (
                    score,
                    row,
                )
            )

        ranked: list[
            dict[str, Any]
        ] = []

        for action, examples in by_action.items():
            examples.sort(
                key=lambda item: item[
                    0
                ],
                reverse=True,
            )

            strongest = examples[
                :3
            ]

            confidence = (
                sum(
                    item[
                        0
                    ]
                    for item in strongest
                )
                / len(
                    strongest
                )
            )

            best = strongest[
                0
            ][
                1
            ]

            ranked.append(
                {
                    "action":
                        action,

                    "confidence":
                        confidence,

                    "best_example":
                        str(
                            best[
                                "request"
                            ]
                        ),

                    "best_source":
                        str(
                            best[
                                "source_type"
                            ]
                        ),

                    "attempts":
                        len(
                            examples
                        ),
                }
            )

        ranked.sort(
            key=lambda item: item[
                "confidence"
            ],
            reverse=True,
        )

        return ranked[
            : max(
                1,
                int(
                    limit
                ),
            )
        ]

    def stats(
        self,
    ) -> dict[str, Any]:
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            COUNT(*) AS attempts,
                            COUNT(DISTINCT action)
                                AS actions,
                            SUM(
                                CASE
                                    WHEN reward > 0
                                    THEN 1
                                    ELSE 0
                                END
                            ) AS positive,
                            SUM(
                                CASE
                                    WHEN reward < 0
                                    THEN 1
                                    ELSE 0
                                END
                            ) AS negative,
                            COALESCE(
                                AVG(reward),
                                0
                            ) AS average_reward,
                            COALESCE(
                                AVG(elapsed_seconds),
                                0
                            ) AS average_elapsed
                        FROM {}.memories
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                aggregate = cursor.fetchone()

                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            source_type,
                            COUNT(*) AS n
                        FROM {}.memories
                        GROUP BY source_type
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                source_rows = cursor.fetchall()

        aggregate = aggregate or {
            "attempts": 0,
            "actions": 0,
            "positive": 0,
            "negative": 0,
            "average_reward": 0,
            "average_elapsed": 0,
        }

        sources = {
            str(
                row[
                    "source_type"
                ]
            ):
            int(
                row[
                    "n"
                ]
            )
            for row in source_rows
        }

        return {
            "database":
                "postgresql:sophyane/"
                + self.schema,

            "learned_executions":
                int(
                    aggregate[
                        "attempts"
                    ]
                    or 0
                ),

            "distinct_actions":
                int(
                    aggregate[
                        "actions"
                    ]
                    or 0
                ),

            "positive_outcomes":
                int(
                    aggregate[
                        "positive"
                    ]
                    or 0
                ),

            "negative_outcomes":
                int(
                    aggregate[
                        "negative"
                    ]
                    or 0
                ),

            "average_reward":
                float(
                    aggregate[
                        "average_reward"
                    ]
                    or 0
                ),

            "average_elapsed":
                float(
                    aggregate[
                        "average_elapsed"
                    ]
                    or 0
                ),

            "sources":
                sources,
        }

    def store_trace(
        self,
        payload: dict[str, Any],
    ) -> None:
        created_at_raw = payload.get(
            "created_at"
        )

        created_at = (
            time.time()
            if created_at_raw is None
            else float(
                created_at_raw
            )
        )

        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        INSERT INTO
                        {}.learned_execution_traces (
                            trace_id,
                            request,
                            action,
                            status,
                            reward,
                            quality_reward,
                            failure_category,
                            quality_signals,
                            result,
                            elapsed_seconds,
                            workspace_before,
                            workspace_after,
                            created_at
                        )
                        VALUES (
                            %s, %s, %s, %s, %s,
                            %s, %s, %s, %s, %s,
                            %s, %s, %s
                        )
                        ON CONFLICT (trace_id)
                        DO UPDATE SET
                            request =
                                EXCLUDED.request,
                            action =
                                EXCLUDED.action,
                            status =
                                EXCLUDED.status,
                            reward =
                                EXCLUDED.reward,
                            quality_reward =
                                EXCLUDED.quality_reward,
                            failure_category =
                                EXCLUDED.failure_category,
                            quality_signals =
                                EXCLUDED.quality_signals,
                            result =
                                EXCLUDED.result,
                            elapsed_seconds =
                                EXCLUDED.elapsed_seconds,
                            workspace_before =
                                EXCLUDED.workspace_before,
                            workspace_after =
                                EXCLUDED.workspace_after,
                            created_at =
                                EXCLUDED.created_at
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        str(
                            payload.get(
                                "trace_id"
                            )
                            or ""
                        ),
                        str(
                            payload.get(
                                "request"
                            )
                            or ""
                        ),
                        str(
                            payload.get(
                                "action"
                            )
                            or
                            "EXECUTE_STRUCTURED_TASK"
                        ),
                        str(
                            payload.get(
                                "status"
                            )
                            or "unknown"
                        ),
                        float(
                            payload.get(
                                "reward"
                            )
                            or 0.0
                        ),
                        float(
                            payload.get(
                                "quality_reward"
                            )
                            or 0.0
                        ),
                        str(
                            payload.get(
                                "failure_category"
                            )
                            or ""
                        ),
                        Jsonb(
                            payload.get(
                                "quality_signals"
                            )
                            or []
                        ),
                        str(
                            payload.get(
                                "result"
                            )
                            or ""
                        ),
                        float(
                            payload.get(
                                "elapsed_seconds"
                            )
                            or 0.0
                        ),
                        Jsonb(
                            payload.get(
                                "workspace_before"
                            )
                            or {}
                        ),
                        Jsonb(
                            payload.get(
                                "workspace_after"
                            )
                            or {}
                        ),
                        created_at,
                    ),
                )

            connection.commit()

    def list_traces(
        self,
        *,
        limit: int = 10,
    ) -> list[dict[str, Any]]:
        count = max(
            1,
            int(
                limit
            ),
        )

        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            trace_id,
                            request,
                            action,
                            status,
                            reward,
                            quality_reward,
                            failure_category,
                            quality_signals,
                            result,
                            elapsed_seconds,
                            workspace_before,
                            workspace_after,
                            created_at
                        FROM {}.learned_execution_traces
                        ORDER BY created_at DESC
                        LIMIT %s
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        count,
                    ),
                )

                rows = cursor.fetchall()

        return [
            dict(
                row
            )
            for row in rows
        ]


    def import_memory(
        self,
        payload: dict[str, Any],
    ) -> None:
        """Import one SQLite memory while preserving its identity."""
        source = str(
            payload.get(
                "source_type"
            )
            or "unknown"
        )

        if source not in SOURCE_WEIGHTS:
            source = "unknown"

        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        INSERT INTO {}.memories (
                            id,
                            request,
                            state,
                            action,
                            result,
                            reward,
                            confidence,
                            elapsed_seconds,
                            source_type,
                            created_at
                        )
                        VALUES (
                            %s, %s, %s, %s, %s,
                            %s, %s, %s, %s, %s
                        )
                        ON CONFLICT (id)
                        DO UPDATE SET
                            request =
                                EXCLUDED.request,
                            state =
                                EXCLUDED.state,
                            action =
                                EXCLUDED.action,
                            result =
                                EXCLUDED.result,
                            reward =
                                EXCLUDED.reward,
                            confidence =
                                EXCLUDED.confidence,
                            elapsed_seconds =
                                EXCLUDED.elapsed_seconds,
                            source_type =
                                EXCLUDED.source_type,
                            created_at =
                                EXCLUDED.created_at
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    ),
                    (
                        int(
                            payload[
                                "id"
                            ]
                        ),
                        str(
                            payload.get(
                                "request"
                            )
                            or ""
                        ),
                        str(
                            payload.get(
                                "state"
                            )
                            or ""
                        ),
                        str(
                            payload.get(
                                "action"
                            )
                            or ""
                        ),
                        str(
                            payload.get(
                                "result"
                            )
                            or ""
                        ),
                        float(
                            payload.get(
                                "reward"
                            )
                            or 0.0
                        ),
                        float(
                            payload.get(
                                "confidence"
                            )
                            or 0.0
                        ),
                        float(
                            payload.get(
                                "elapsed_seconds"
                            )
                            or 0.0
                        ),
                        source,
                        float(
                            payload.get(
                                "created_at"
                            )
                            or 0.0
                        ),
                    ),
                )

            connection.commit()

    def synchronize_memory_identity(
        self,
    ) -> None:
        """Advance the memories identity after explicit-ID imports."""
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        SELECT pg_get_serial_sequence(
                            %s,
                            'id'
                        ) AS sequence_name
                        """
                    ),
                    (
                        (
                            self.schema
                            + ".memories"
                        ),
                    ),
                )

                row = cursor.fetchone()

                sequence_name = (
                    str(
                        row[
                            "sequence_name"
                        ]
                    )
                    if row
                    and row.get(
                        "sequence_name"
                    )
                    else ""
                )

                if sequence_name:
                    cursor.execute(
                        sql.SQL(
                            """
                            SELECT COALESCE(
                                MAX(id),
                                0
                            ) AS maximum_id
                            FROM {}.memories
                            """
                        ).format(
                            sql.Identifier(
                                self.schema
                            )
                        )
                    )

                    maximum = cursor.fetchone()

                    maximum_id = int(
                        (
                            maximum
                            or {}
                        ).get(
                            "maximum_id"
                        )
                        or 0
                    )

                    if maximum_id > 0:
                        cursor.execute(
                            """
                            SELECT setval(
                                %s::regclass,
                                %s,
                                true
                            )
                            """,
                            (
                                sequence_name,
                                maximum_id,
                            ),
                        )
                    else:
                        cursor.execute(
                            """
                            SELECT setval(
                                %s::regclass,
                                1,
                                false
                            )
                            """,
                            (
                                sequence_name,
                            ),
                        )

            connection.commit()

    def export_snapshot(
        self,
    ) -> dict[str, list[dict[str, Any]]]:
        """Return canonical PostgreSQL SLI rows for migration verification."""
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            id,
                            request,
                            state,
                            action,
                            result,
                            reward,
                            confidence,
                            elapsed_seconds,
                            source_type,
                            created_at
                        FROM {}.memories
                        ORDER BY id
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                memories = [
                    dict(
                        row
                    )
                    for row in cursor.fetchall()
                ]

                cursor.execute(
                    sql.SQL(
                        """
                        SELECT
                            trace_id,
                            request,
                            action,
                            status,
                            reward,
                            quality_reward,
                            failure_category,
                            quality_signals,
                            result,
                            elapsed_seconds,
                            workspace_before,
                            workspace_after,
                            created_at
                        FROM {}.learned_execution_traces
                        ORDER BY trace_id
                        """
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

                traces = [
                    dict(
                        row
                    )
                    for row in cursor.fetchall()
                ]

        return {
            "memories":
                memories,

            "traces":
                traces,
        }


    def drop_schema(
        self,
    ) -> None:
        """Drop this SLI schema explicitly.

        Intended for controlled rollback and disposable-test cleanup.
        """
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL(
                        "DROP SCHEMA IF EXISTS {} CASCADE"
                    ).format(
                        sql.Identifier(
                            self.schema
                        )
                    )
                )

            connection.commit()

    def schema_exists(
        self,
    ) -> bool:
        """Return whether this PostgreSQL schema currently exists."""
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT EXISTS (
                        SELECT 1
                        FROM information_schema.schemata
                        WHERE schema_name = %s
                    ) AS present
                    """,
                    (
                        self.schema,
                    ),
                )

                row = cursor.fetchone()

        return bool(
            row
            and row.get(
                "present"
            )
        )
