"""Application factory: websites + Android / HarmonyOS / iOS / desktop scaffolds."""

from __future__ import annotations

import json
import re
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


SUPPORTED_TARGETS = (
    "web",
    "android",
    "harmony",
    "ios",
    "desktop_python",
    "api_python",
)


@dataclass
class AppScaffoldResult:
    ok: bool
    target: str
    name: str
    path: str
    files: list[str]
    message: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _slug(name: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9._-]+", "-", name.strip()).strip("-_.")
    return cleaned or f"sophyane-app-{int(time.time())}"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def create_app(
    target: str,
    name: str,
    *,
    output_dir: str | Path | None = None,
    description: str = "",
) -> AppScaffoldResult:
    target = (target or "").lower().strip()
    if target not in SUPPORTED_TARGETS:
        return AppScaffoldResult(
            False,
            target,
            name,
            "",
            [],
            f"Unsupported target {target!r}. Choose from: {', '.join(SUPPORTED_TARGETS)}",
        )

    slug = _slug(name)
    root = Path(output_dir or Path.cwd() / "sophyane-apps" / slug).expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    files: list[str] = []
    desc = description or f"{name} generated by Sophyane AI Kernel"

    if target == "web":
        files += _scaffold_web(root, name, desc)
    elif target == "android":
        files += _scaffold_android(root, name, desc)
    elif target == "harmony":
        files += _scaffold_harmony(root, name, desc)
    elif target == "ios":
        files += _scaffold_ios(root, name, desc)
    elif target == "desktop_python":
        files += _scaffold_desktop_python(root, name, desc)
    elif target == "api_python":
        files += _scaffold_api_python(root, name, desc)

    meta = {
        "name": name,
        "slug": slug,
        "target": target,
        "description": desc,
        "created_by": "sophyane-ai-kernel",
        "created_at": time.time(),
        "files": files,
    }
    meta_path = root / "sophyane-app.json"
    _write(meta_path, json.dumps(meta, indent=2) + "\n")
    files.append(str(meta_path.relative_to(root)))

    return AppScaffoldResult(
        True,
        target,
        name,
        str(root),
        files,
        f"Created {target} scaffold at {root}",
    )


def _scaffold_web(root: Path, name: str, desc: str) -> list[str]:
    rel: list[str] = []
    index = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{name}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <main class="card">
    <h1>{name}</h1>
    <p>{desc}</p>
    <p>Talk to Sophyane Hardware API:</p>
    <pre id="out">Connecting…</pre>
  </main>
  <script src="app.js"></script>
</body>
</html>
"""
    css = """:root { font-family: system-ui, sans-serif; color: #0f172a; background: #f8fafc; }
main.card { max-width: 42rem; margin: 3rem auto; padding: 1.5rem; background: white;
  border-radius: 12px; box-shadow: 0 8px 30px rgba(15,23,42,.08); }
pre { background: #0f172a; color: #e2e8f0; padding: 1rem; border-radius: 8px; overflow: auto; }
"""
    js = """const API = (globalThis.SOPHYANE_API || 'http://127.0.0.1:8770');
const out = document.getElementById('out');
async function main() {
  try {
    const res = await fetch(API + '/v1/hardware/health');
    const data = await res.json();
    out.textContent = JSON.stringify(data, null, 2);
  } catch (err) {
    out.textContent = 'API offline: ' + err + '\\nStart: sophyane --hardware-api';
  }
}
main();
"""
    for path, content in (
        ("index.html", index),
        ("styles.css", css),
        ("app.js", js),
        ("README.md", f"# {name}\n\n{desc}\n\nOpen `index.html` or serve this folder.\n"),
    ):
        _write(root / path, content)
        rel.append(path)
    return rel


def _scaffold_android(root: Path, name: str, desc: str) -> list[str]:
    pkg = "com.sophyane." + re.sub(r"[^a-z0-9]", "", name.lower())[:24] or "app"
    rel: list[str] = []
    manifest = f"""<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="{pkg}">
  <uses-permission android:name="android.permission.INTERNET" />
  <application android:label="{name}" android:usesCleartextTraffic="true">
    <activity android:name=".MainActivity" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
  </application>
</manifest>
"""
    activity = f"""package {pkg};

import android.app.Activity;
import android.os.Bundle;
import android.widget.TextView;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

/** Sophyane-generated Android entry. Wire to Sophyane Hardware API. */
public class MainActivity extends Activity {{
  @Override protected void onCreate(Bundle savedInstanceState) {{
    super.onCreate(savedInstanceState);
    TextView tv = new TextView(this);
    tv.setText("{name}\\n{desc}\\n\\nFetching Sophyane health…");
    setContentView(tv);
    new Thread(() -> {{
      try {{
        URL url = new URL("http://10.0.2.2:8770/v1/hardware/health");
        HttpURLConnection c = (HttpURLConnection) url.openConnection();
        BufferedReader br = new BufferedReader(new InputStreamReader(c.getInputStream()));
        StringBuilder sb = new StringBuilder();
        String line; while ((line = br.readLine()) != null) sb.append(line);
        runOnUiThread(() -> tv.setText("{name}\\n" + sb));
      }} catch (Exception e) {{
        runOnUiThread(() -> tv.setText("API offline: " + e.getMessage()));
      }}
    }}).start();
  }}
}}
"""
    gradle = f"""// Sophyane Android scaffold for {name}
// Open in Android Studio. Point API host to your Sophyane --hardware-api server.
plugins {{
    id 'com.android.application' version '8.2.0' apply false
}}
"""
    readme = f"""# {name} (Android)

{desc}

## Build
1. Open this folder in Android Studio (or copy into an existing project).
2. Run `sophyane --hardware-api` on your PC.
3. Emulator uses `10.0.2.2:8770` to reach the host API.

Generated by Sophyane AI Kernel.
"""
    mapping = {
        "README.md": readme,
        "settings.gradle": "rootProject.name = '" + _slug(name) + "'\n",
        "build.gradle": gradle,
        "app/src/main/AndroidManifest.xml": manifest,
        f"app/src/main/java/{pkg.replace('.', '/')}/MainActivity.java": activity,
    }
    for path, content in mapping.items():
        _write(root / path, content)
        rel.append(path)
    return rel


def _scaffold_harmony(root: Path, name: str, desc: str) -> list[str]:
    """HarmonyOS / OpenHarmony lightweight Stage model scaffold (ArkTS-oriented)."""
    rel: list[str] = []
    entry = f"""// {name} — HarmonyOS / OpenHarmony scaffold (ArkTS-style)
// Connects to Sophyane Hardware API over HTTP.

export struct MainPage {{
  @State message: string = '{name} ready';

  aboutToAppear() {{
    // In a real project use @ohos.net.http to call SOPHYANE_API
    this.message = '{name}: wire httpRequest to http://127.0.0.1:8770/v1/hardware/health';
  }}

  build() {{
    Column() {{
      Text(this.message)
    }}
  }}
}}
"""
    config = {
        "app": {"bundleName": f"com.sophyane.{_slug(name).replace('-', '')}", "vendor": "Sophyane"},
        "deviceTypes": ["phone", "tablet", "2in1"],
        "sophyane_api": "http://127.0.0.1:8770",
        "description": desc,
    }
    readme = f"""# {name} (HarmonyOS / OpenHarmony)

{desc}

## Next steps
1. Import into DevEco Studio (HarmonyOS) or OpenHarmony toolchain.
2. Replace the stub HTTP call with `@ohos.net.http`.
3. Point `sophyane_api` at your Sophyane Hardware API host.

Generated by Sophyane AI Kernel.
"""
    for path, content in (
        ("README.md", readme),
        ("entry/src/main/ets/pages/Index.ets", entry),
        ("AppScope/app.json5", json.dumps(config, indent=2) + "\n"),
    ):
        _write(root / path, content if isinstance(content, str) else content)
        rel.append(path)
    return rel


def _scaffold_ios(root: Path, name: str, desc: str) -> list[str]:
    rel: list[str] = []
    swift = f"""import SwiftUI

// {name} — Sophyane iOS scaffold
// Talks to Sophyane Hardware API (set SOPHYANE_API / Info.plist).

@main
struct SophyaneApp: App {{
  var body: some Scene {{
    WindowGroup {{ ContentView() }}
  }}
}}

struct ContentView: View {{
  @State private var status = "{name}\\n{desc}\\nLoading…"
  var body: some View {{
    ScrollView {{ Text(status).padding() }}
      .task {{ await load() }}
  }}
  func load() async {{
    guard let url = URL(string: "http://127.0.0.1:8770/v1/hardware/health") else {{ return }}
    do {{
      let (data, _) = try await URLSession.shared.data(from: url)
      status = String(data: data, encoding: .utf8) ?? "empty"
    }} catch {{
      status = "API offline: \\(error.localizedDescription)\\nStart sophyane --hardware-api on a paired host."
    }}
  }}
}}
"""
    readme = f"""# {name} (iOS)

{desc}

## Build
1. Create an Xcode App project and drop `ContentView.swift` in, or open as a package.
2. For device/simulator ATS, allow local networking or use HTTPS reverse proxy.
3. Prefer a paired Mac/Linux host running `sophyane --hardware-api`.

Generated by Sophyane AI Kernel.
"""
    for path, content in (
        ("README.md", readme),
        ("Sources/App/ContentView.swift", swift),
        ("Package.swift", """// swift-tools-version:5.9
import PackageDescription
let package = Package(name: "SophyaneApp", platforms: [.iOS(.v16)], products: [], targets: [])
"""),
    ):
        _write(root / path, content)
        rel.append(path)
    return rel


def _scaffold_desktop_python(root: Path, name: str, desc: str) -> list[str]:
    rel: list[str] = []
    app = f'''#!/usr/bin/env python3
"""{name} — desktop helper using Sophyane Hardware API."""
from __future__ import annotations
import json, urllib.request

API = "http://127.0.0.1:8770"

def main() -> None:
    print("{name}")
    print("{desc}")
    try:
        with urllib.request.urlopen(API + "/v1/hardware/health", timeout=5) as r:
            print(json.dumps(json.loads(r.read().decode()), indent=2))
    except Exception as exc:
        print("API offline:", exc)
        print("Start: sophyane --hardware-api")

if __name__ == "__main__":
    main()
'''
    for path, content in (
        ("main.py", app),
        ("README.md", f"# {name}\n\n{desc}\n\n```bash\npython main.py\n```\n"),
        ("requirements.txt", "# Uses stdlib only\n"),
    ):
        _write(root / path, content)
        rel.append(path)
    return rel


def _scaffold_api_python(root: Path, name: str, desc: str) -> list[str]:
    rel: list[str] = []
    server = f'''#!/usr/bin/env python3
"""{name} — minimal API service scaffold (stdlib)."""
from http.server import BaseHTTPRequestHandler, HTTPServer
import json

class H(BaseHTTPRequestHandler):
    def do_GET(self):
        body = json.dumps({{"service": "{name}", "ok": True, "desc": "{desc}"}}).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(body)
    def log_message(self, *args):
        return

if __name__ == "__main__":
    print("Serving {name} on http://127.0.0.1:8088")
    HTTPServer(("127.0.0.1", 8088), H).serve_forever()
'''
    for path, content in (
        ("server.py", server),
        ("README.md", f"# {name}\n\n{desc}\n\n```bash\npython server.py\n```\n"),
    ):
        _write(root / path, content)
        rel.append(path)
    return rel
