"""Coverage-driven curriculum generation for Sophyane SLI.

The engine examines successful learning history and code-memory contracts,
selects weak capability families, creates deterministic novel instructions,
and records curriculum outcomes.

It does not call a local or cloud LLM.
"""
from __future__ import annotations

import hashlib
import json
import math
import random
import re
import time

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable


MEMORY_ROOT = (
    Path.home()
    / ".local/share/sophyane/code_memory"
)

CONTINUOUS_ROOT = (
    Path.home()
    / ".local/share/sophyane/continuous_sli"
)

EVENTS_FILE = CONTINUOUS_ROOT / "events.jsonl"

CURRICULUM_ROOT = (
    MEMORY_ROOT
    / "coverage_curriculum"
)

STATE_FILE = CURRICULUM_ROOT / "state.json"
EVENT_FILE = CURRICULUM_ROOT / "events.jsonl"
REQUEST_FILE = CURRICULUM_ROOT / "requests.jsonl"

DEFAULT_TARGET_SUCCESSES = 6
RECENT_REQUEST_LIMIT = 300
MAX_FAILURE_STREAK = 4


@dataclass(frozen=True)
class CurriculumFamily:
    name: str
    capabilities: tuple[str, ...]
    product_kind: str
    request_patterns: tuple[str, ...]
    concepts: tuple[str, ...]
    interfaces: tuple[str, ...] = ()
    validators: tuple[str, ...] = ()
    priority: float = 1.0


@dataclass
class FamilyStats:
    family: str
    successes: int = 0
    failures: int = 0
    recent_failures: int = 0
    chunks_learned: int = 0
    last_attempt: float = 0.0
    last_success: float = 0.0
    memory_evidence: int = 0
    score: float = 0.0


@dataclass
class CurriculumState:
    version: int = 1
    iteration: int = 0
    seed: int = 0
    family_cursor: dict[str, int] = field(default_factory=dict)
    failure_streaks: dict[str, int] = field(default_factory=dict)
    cooldown_until: dict[str, float] = field(default_factory=dict)
    recent_requests: list[str] = field(default_factory=list)
    family_successes: dict[str, int] = field(default_factory=dict)
    family_failures: dict[str, int] = field(default_factory=dict)


# These are capability families, not fixed products. Requests are generated by
# combining patterns, concepts and interface requirements.
FAMILIES: tuple[CurriculumFamily, ...] = (
    CurriculumFamily(
        name="informational_site",
        capabilities=(
            "document_shell",
            "presentation",
            "topic_retrieval",
            "source_attribution",
            "responsive_layout",
        ),
        product_kind="browser",
        request_patterns=(
            "make an internet-grounded responsive website about {concept}",
            "create a factual self-contained webpage explaining {concept}",
            "build an attributed informational site on {concept}",
        ),
        concepts=(
            "renewable energy in Pakistan",
            "water conservation",
            "steel manufacturing",
            "urban transport",
            "agricultural technology",
            "public health",
            "wildlife conservation",
            "computer networking",
            "space exploration",
            "climate adaptation",
        ),
        validators=(
            "topic_identity",
            "source_attribution",
            "complete_html",
        ),
        priority=0.8,
    ),
    CurriculumFamily(
        name="form_application",
        capabilities=(
            "document_shell",
            "application_state",
            "user_input",
            "rules_validation",
            "rendering",
            "feedback",
        ),
        product_kind="browser",
        request_patterns=(
            "create a self-contained {concept} form with validation and reset",
            "build an accessible browser {concept} workflow with live validation",
            "make an interactive {concept} form that saves state locally",
        ),
        concepts=(
            "customer registration",
            "school admission",
            "medical appointment",
            "inventory intake",
            "employee onboarding",
            "event booking",
            "expense submission",
            "maintenance request",
        ),
        interfaces=(
            "input",
            "validation",
            "submit",
            "reset",
        ),
        priority=1.1,
    ),
    CurriculumFamily(
        name="dashboard",
        capabilities=(
            "document_shell",
            "application_state",
            "data_model",
            "rendering",
            "filtering",
            "sorting",
            "progress_feedback",
        ),
        product_kind="browser",
        request_patterns=(
            "build a self-contained {concept} dashboard with filters and summary cards",
            "create an interactive {concept} browser dashboard with sortable data",
            "make a responsive {concept} analytics page with charts and filtering",
        ),
        concepts=(
            "sales",
            "warehouse inventory",
            "energy consumption",
            "school attendance",
            "project progress",
            "hospital operations",
            "manufacturing output",
            "personal finance",
        ),
        priority=1.3,
    ),
    CurriculumFamily(
        name="crud_application",
        capabilities=(
            "document_shell",
            "application_state",
            "data_model",
            "user_input",
            "create_record",
            "update_record",
            "delete_record",
            "persistence",
        ),
        product_kind="browser",
        request_patterns=(
            "build a self-contained {concept} manager with add edit delete and search",
            "create an offline browser {concept} CRUD application using local storage",
            "make a responsive {concept} registry with filtering and persistence",
        ),
        concepts=(
            "contact",
            "inventory",
            "student",
            "task",
            "book",
            "supplier",
            "maintenance ticket",
            "product catalogue",
        ),
        priority=1.5,
    ),
    CurriculumFamily(
        name="language_exercise",
        capabilities=(
            "document_shell",
            "data_model",
            "rules_validation",
            "user_input",
            "progress_feedback",
            "score",
            "lifecycle",
        ),
        product_kind="browser",
        request_patterns=(
            "make a complete interactive {concept} exercise with score next and restart",
            "create a child-friendly {concept} quiz with feedback and progress",
            "build a self-contained {concept} learning game with several questions",
        ),
        concepts=(
            "missing-word English",
            "spelling",
            "basic vocabulary",
            "sentence completion",
            "synonym matching",
            "capital city",
            "multiplication",
            "science facts",
        ),
        priority=1.0,
    ),
    CurriculumFamily(
        name="action_game",
        capabilities=(
            "document_shell",
            "application_state",
            "directional_input",
            "timed_loop",
            "collision_detection",
            "canvas_rendering",
            "score",
            "restart",
        ),
        product_kind="browser",
        request_patterns=(
            "create a playable self-contained {concept} browser game with score and restart",
            "build a keyboard-controlled {concept} game using canvas and a timed loop",
            "make a responsive {concept} arcade game with collision detection",
        ),
        concepts=(
            "paddle ball",
            "brick breaker",
            "maze escape",
            "falling objects",
            "space dodger",
            "lane runner",
            "target catching",
            "balloon pop",
        ),
        priority=1.8,
    ),
    CurriculumFamily(
        name="simulation",
        capabilities=(
            "document_shell",
            "application_state",
            "timed_loop",
            "parameter_controls",
            "rendering",
            "reset",
        ),
        product_kind="browser",
        request_patterns=(
            "build an interactive {concept} simulation with adjustable parameters",
            "create a self-contained visual {concept} simulator with pause and reset",
            "make a browser demonstration of {concept} with live controls",
        ),
        concepts=(
            "projectile motion",
            "traffic flow",
            "solar-system orbit",
            "population growth",
            "spring oscillation",
            "water tank filling",
            "compound interest",
            "heat diffusion",
        ),
        priority=1.4,
    ),
    CurriculumFamily(
        name="editor",
        capabilities=(
            "document_shell",
            "application_state",
            "user_input",
            "editing",
            "undo_redo",
            "persistence",
            "export",
        ),
        product_kind="browser",
        request_patterns=(
            "create a self-contained {concept} editor with undo redo and export",
            "build an offline browser {concept} editor with local persistence",
            "make an accessible {concept} editing application with keyboard shortcuts",
        ),
        concepts=(
            "markdown",
            "plain text",
            "JSON",
            "SVG drawing",
            "note",
            "resume",
            "diagram",
            "colour palette",
        ),
        priority=1.3,
    ),
    CurriculumFamily(
        name="data_visualization",
        capabilities=(
            "document_shell",
            "data_model",
            "rendering",
            "charting",
            "filtering",
            "responsive_layout",
        ),
        product_kind="browser",
        request_patterns=(
            "create a self-contained visualization of {concept} with interactive filters",
            "build a responsive {concept} chart explorer using sample data",
            "make a browser visualizer for {concept} with multiple views",
        ),
        concepts=(
            "monthly energy usage",
            "regional population",
            "factory production",
            "portfolio performance",
            "weather observations",
            "store sales",
            "student grades",
            "transport demand",
        ),
        priority=1.2,
    ),
    CurriculumFamily(
        name="python_policy",
        capabilities=(
            "python_module",
            "policy_engine",
            "deterministic_decision",
            "validation",
        ),
        product_kind="python",
        request_patterns=(
            "create exactly one Python file implementing a deterministic {concept}",
            "write one typed Python module for {concept} with input validation",
        ),
        concepts=(
            "provider routing policy",
            "retry budget controller",
            "rate-limit policy",
            "feature-flag evaluator",
            "task-priority policy",
            "resource allocation policy",
        ),
        priority=1.1,
    ),
    CurriculumFamily(
        name="python_security",
        capabilities=(
            "python_module",
            "path_safety",
            "canonicalization",
            "audit",
            "validation",
        ),
        product_kind="python",
        request_patterns=(
            "create exactly one Python file implementing a secure {concept}",
            "write one standalone Python module for {concept} with safe failure behavior",
        ),
        concepts=(
            "sandbox path resolver",
            "tamper-evident audit chain",
            "safe archive extractor",
            "secret redaction filter",
            "permission rule evaluator",
            "request scope guard",
        ),
        priority=1.5,
    ),
    CurriculumFamily(
        name="python_orchestration",
        capabilities=(
            "python_module",
            "orchestration",
            "retry",
            "validation",
            "structured_result",
        ),
        product_kind="python",
        request_patterns=(
            "create exactly one Python file implementing {concept}",
            "write one deterministic Python orchestration module for {concept}",
        ),
        concepts=(
            "local-first validated execution",
            "bounded retry controller",
            "dependency scheduler",
            "capability closure solver",
            "task state machine",
            "result aggregation pipeline",
        ),
        priority=1.4,
    ),
    CurriculumFamily(
        name="api_service",
        capabilities=(
            "python_module",
            "http_api",
            "routing",
            "validation",
            "structured_response",
        ),
        product_kind="python",
        request_patterns=(
            "create a minimal Python {concept} with one health endpoint and validation",
            "build a small typed Python {concept} returning JSON responses",
        ),
        concepts=(
            "FastAPI service",
            "Starlette service",
            "Flask API",
            "HTTP health service",
        ),
        priority=1.2,
    ),
)


FAMILY_BY_NAME = {
    family.name: family
    for family in FAMILIES
}


def _append_jsonl(
    path: Path,
    record: dict[str, Any],
) -> None:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with path.open(
        "a",
        encoding="utf-8",
    ) as handle:
        handle.write(
            json.dumps(
                record,
                ensure_ascii=False,
            )
            + "\n"
        )


def _read_jsonl(
    path: Path,
) -> list[dict[str, Any]]:
    if not path.is_file():
        return []

    output = []

    for line in path.read_text(
        encoding="utf-8",
        errors="replace",
    ).splitlines():
        if not line.strip():
            continue

        try:
            value = json.loads(line)
        except json.JSONDecodeError:
            continue

        if isinstance(value, dict):
            output.append(value)

    return output


def load_state() -> CurriculumState:
    CURRICULUM_ROOT.mkdir(
        parents=True,
        exist_ok=True,
    )

    if not STATE_FILE.is_file():
        return CurriculumState(
            seed=int(time.time()),
        )

    try:
        payload = json.loads(
            STATE_FILE.read_text(
                encoding="utf-8",
            )
        )

        allowed = {
            field_name
            for field_name in (
                "version",
                "iteration",
                "seed",
                "family_cursor",
                "failure_streaks",
                "cooldown_until",
                "recent_requests",
                "family_successes",
                "family_failures",
            )
        }

        return CurriculumState(
            **{
                key: value
                for key, value in payload.items()
                if key in allowed
            }
        )

    except Exception:
        return CurriculumState(
            seed=int(time.time()),
        )


def save_state(
    state: CurriculumState,
) -> None:
    CURRICULUM_ROOT.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = STATE_FILE.with_suffix(
        ".json.tmp"
    )

    temporary.write_text(
        json.dumps(
            asdict(state),
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    temporary.replace(
        STATE_FILE
    )


def _normalise_request(
    value: str,
) -> str:
    return " ".join(
        str(value or "")
        .lower()
        .strip()
        .split()
    )


def classify_request_family(
    request: str,
) -> str | None:
    low = _normalise_request(
        request
    )

    rules = (
        (
            "action_game",
            (
                "game",
                "arcade",
                "collision",
                "paddle",
                "maze",
            ),
        ),
        (
            "language_exercise",
            (
                "quiz",
                "exercise",
                "missing word",
                "spelling",
                "vocabulary",
            ),
        ),
        (
            "dashboard",
            (
                "dashboard",
                "analytics",
                "summary cards",
            ),
        ),
        (
            "crud_application",
            (
                "crud",
                "add edit delete",
                "registry",
                "manager",
            ),
        ),
        (
            "form_application",
            (
                "form",
                "registration",
                "booking",
                "submission",
            ),
        ),
        (
            "simulation",
            (
                "simulation",
                "simulator",
            ),
        ),
        (
            "editor",
            (
                "editor",
                "undo redo",
            ),
        ),
        (
            "data_visualization",
            (
                "visualization",
                "chart",
                "visualizer",
            ),
        ),
        (
            "api_service",
            (
                "fastapi",
                "starlette",
                "flask api",
                "health endpoint",
            ),
        ),
        (
            "python_security",
            (
                "sandbox",
                "audit chain",
                "redaction",
                "permission",
                "safe archive",
            ),
        ),
        (
            "python_policy",
            (
                "policy",
                "feature-flag",
                "rate-limit",
            ),
        ),
        (
            "python_orchestration",
            (
                "retry controller",
                "scheduler",
                "state machine",
                "capability closure",
                "orchestration",
            ),
        ),
        (
            "informational_site",
            (
                "website",
                "webpage",
                "informational site",
                "factual",
            ),
        ),
    )

    for family, terms in rules:
        if any(
            term in low
            for term in terms
        ):
            return family

    return None


def load_run_statistics() -> dict[str, FamilyStats]:
    stats = {
        family.name:
            FamilyStats(
                family=family.name
            )
        for family in FAMILIES
    }

    events = _read_jsonl(
        EVENTS_FILE
    )

    recent_events = events[-100:]

    for event in events:
        request = str(
            event.get("request")
            or ""
        )

        family_name = (
            event.get("curriculum_family")
            or classify_request_family(
                request
            )
        )

        if family_name not in stats:
            continue

        item = stats[family_name]
        success = bool(
            event.get("success")
        )

        if success:
            item.successes += 1
            item.chunks_learned += int(
                event.get("chunks_learned")
                or 0
            )
            item.last_success = max(
                item.last_success,
                float(
                    event.get("finished_at")
                    or event.get("timestamp")
                    or 0.0
                ),
            )
        else:
            item.failures += 1

        item.last_attempt = max(
            item.last_attempt,
            float(
                event.get("finished_at")
                or event.get("timestamp")
                or 0.0
            ),
        )

    for event in recent_events:
        request = str(
            event.get("request")
            or ""
        )

        family_name = (
            event.get("curriculum_family")
            or classify_request_family(
                request
            )
        )

        if (
            family_name in stats
            and not bool(
                event.get("success")
            )
        ):
            stats[
                family_name
            ].recent_failures += 1

    return stats


def _chunk_meta_values(
    meta: dict[str, Any],
) -> set[str]:
    values = set()

    for key in (
        "provides",
        "roles",
        "exports",
        "requires",
    ):
        raw = meta.get(key) or []

        if isinstance(raw, str):
            raw = [raw]

        for value in raw:
            value = str(
                value
            ).strip().lower()

            if value:
                values.add(value)

    domain = str(
        meta.get("domain")
        or ""
    ).strip().lower()

    if domain:
        values.add(domain)

    return values


def memory_capability_counts() -> dict[str, int]:
    from sophyane.code_memory.store import (
        ChunkStore,
    )

    store = ChunkStore()

    counts: dict[str, int] = {}

    for chunk in store.chunks.values():
        meta = dict(
            getattr(
                chunk,
                "meta",
                None,
            )
            or {}
        )

        if meta.get("exclude"):
            continue

        for capability in _chunk_meta_values(
            meta
        ):
            counts[capability] = (
                counts.get(
                    capability,
                    0,
                )
                + 1
            )

    return counts


def family_memory_evidence(
    family: CurriculumFamily,
    capability_counts: dict[str, int],
) -> int:
    return sum(
        min(
            10,
            capability_counts.get(
                capability.lower(),
                0,
            ),
        )
        for capability in family.capabilities
    )


def score_families(
    state: CurriculumState,
    *,
    now: float | None = None,
) -> list[FamilyStats]:
    now = (
        float(now)
        if now is not None
        else time.time()
    )

    stats = load_run_statistics()
    capability_counts = (
        memory_capability_counts()
    )

    for family in FAMILIES:
        item = stats[family.name]

        item.memory_evidence = (
            family_memory_evidence(
                family,
                capability_counts,
            )
        )

        target_gap = max(
            0,
            DEFAULT_TARGET_SUCCESSES
            - item.successes,
        )

        evidence_gap = max(
            0,
            len(family.capabilities) * 4
            - item.memory_evidence,
        )

        failure_rate = (
            item.failures
            / max(
                1,
                item.successes
                + item.failures,
            )
        )

        recency_hours = (
            (
                now - item.last_attempt
            )
            / 3600.0
            if item.last_attempt
            else 999.0
        )

        cooldown = float(
            state.cooldown_until.get(
                family.name,
                0.0,
            )
        )

        if cooldown > now:
            item.score = -1_000_000.0
            continue

        # Weakness creates priority, but repeated failures reduce priority so
        # the system explores another family instead of hammering one problem.
        item.score = (
            family.priority * 10.0
            + target_gap * 8.0
            + evidence_gap * 0.8
            + min(
                24.0,
                recency_hours,
            )
            - failure_rate * 18.0
            - item.recent_failures * 4.0
            + math.log1p(
                item.chunks_learned
            )
        )

    return sorted(
        stats.values(),
        key=lambda item: (
            -item.score,
            item.successes,
            item.family,
        ),
    )


def _request_digest(
    request: str,
) -> str:
    return hashlib.sha256(
        _normalise_request(
            request
        ).encode("utf-8")
    ).hexdigest()


def generate_request(
    family_name: str,
    state: CurriculumState,
) -> str:
    family = FAMILY_BY_NAME[
        family_name
    ]

    cursor = int(
        state.family_cursor.get(
            family_name,
            0,
        )
    )

    recent = {
        _normalise_request(
            request
        )
        for request in state.recent_requests
    }

    combinations = []

    for pattern_index, pattern in enumerate(
        family.request_patterns
    ):
        for concept_index, concept in enumerate(
            family.concepts
        ):
            combinations.append(
                (
                    pattern_index,
                    concept_index,
                    pattern.format(
                        concept=concept
                    ),
                )
            )

    # Deterministic rotation with a state seed gives reproducibility while
    # still spreading attempts across combinations.
    rng = random.Random(
        state.seed
        + state.iteration * 1_000_003
        + sum(
            ord(character)
            for character in family_name
        )
    )

    rng.shuffle(
        combinations
    )

    if combinations:
        shift = cursor % len(
            combinations
        )

        combinations = (
            combinations[shift:]
            + combinations[:shift]
        )

    selected = None

    for _pattern, _concept, request in combinations:
        if (
            _normalise_request(request)
            not in recent
        ):
            selected = request
            break

    if selected is None:
        base = combinations[
            cursor % len(combinations)
        ][2]

        # A deterministic variation changes data size and presentation
        # constraints without altering the capability family.
        variations = (
            " Include keyboard accessibility and responsive mobile layout.",
            " Include sample data, reset behavior and clear validation feedback.",
            " Keep it offline-capable and self-contained.",
            " Include an accessible help panel and deterministic test data.",
        )

        selected = (
            base
            + variations[
                state.iteration
                % len(variations)
            ]
        )

    if family.product_kind == "browser":
        if (
            "self-contained" not in selected.lower()
            and "self contained" not in selected.lower()
        ):
            selected += (
                " Produce one self-contained index.html."
            )

    state.family_cursor[
        family_name
    ] = cursor + 1

    state.recent_requests.append(
        selected
    )

    state.recent_requests = (
        state.recent_requests[
            -RECENT_REQUEST_LIMIT:
        ]
    )

    return selected


def choose_next_request(
    state: CurriculumState,
) -> tuple[CurriculumFamily, str, list[FamilyStats]]:
    ranked = score_families(
        state
    )

    available = [
        item
        for item in ranked
        if item.score > -100_000
    ]

    if not available:
        state.cooldown_until.clear()
        available = score_families(
            state
        )

    if not available:
        raise RuntimeError(
            "No curriculum families are available."
        )

    # Choose among the strongest three to avoid starving near-equal families.
    top = available[:3]

    rng = random.Random(
        state.seed
        + state.iteration * 97
    )

    weights = [
        max(
            0.1,
            item.score
            - min(
                candidate.score
                for candidate in top
            )
            + 1.0,
        )
        for item in top
    ]

    chosen_stats = rng.choices(
        top,
        weights=weights,
        k=1,
    )[0]

    family = FAMILY_BY_NAME[
        chosen_stats.family
    ]

    request = generate_request(
        family.name,
        state,
    )

    return family, request, ranked


def record_outcome(
    state: CurriculumState,
    *,
    family: CurriculumFamily,
    request: str,
    success: bool,
    chunks_learned: int,
    elapsed_seconds: float,
    workspace: str,
    report: str,
) -> dict[str, Any]:
    now = time.time()

    state.iteration += 1

    if success:
        state.family_successes[
            family.name
        ] = (
            int(
                state.family_successes.get(
                    family.name,
                    0,
                )
            )
            + 1
        )

        state.failure_streaks[
            family.name
        ] = 0

        state.cooldown_until.pop(
            family.name,
            None,
        )

    else:
        state.family_failures[
            family.name
        ] = (
            int(
                state.family_failures.get(
                    family.name,
                    0,
                )
            )
            + 1
        )

        streak = (
            int(
                state.failure_streaks.get(
                    family.name,
                    0,
                )
            )
            + 1
        )

        state.failure_streaks[
            family.name
        ] = streak

        if streak >= MAX_FAILURE_STREAK:
            # Increasing cooldown stops a broken route from consuming every
            # curriculum iteration.
            cooldown_minutes = min(
                12 * 60,
                15 * (2 ** min(5, streak - MAX_FAILURE_STREAK)),
            )

            state.cooldown_until[
                family.name
            ] = (
                now
                + cooldown_minutes * 60
            )

    save_state(
        state
    )

    record = {
        "timestamp":
            now,

        "iteration":
            state.iteration,

        "family":
            family.name,

        "capabilities":
            list(
                family.capabilities
            ),

        "request":
            request,

        "request_sha256":
            _request_digest(
                request
            ),

        "success":
            bool(success),

        "chunks_learned":
            int(chunks_learned),

        "elapsed_seconds":
            round(
                float(elapsed_seconds),
                3,
            ),

        "workspace":
            workspace,

        "report_excerpt":
            str(report or "")[
                :2_000
            ],

        "failure_streak":
            int(
                state.failure_streaks.get(
                    family.name,
                    0,
                )
            ),

        "cooldown_until":
            float(
                state.cooldown_until.get(
                    family.name,
                    0.0,
                )
            ),
    }

    _append_jsonl(
        EVENT_FILE,
        record,
    )

    _append_jsonl(
        REQUEST_FILE,
        {
            "timestamp":
                now,

            "iteration":
                state.iteration,

            "family":
                family.name,

            "request":
                request,

            "success":
                bool(success),
        },
    )

    return record


def coverage_report() -> dict[str, Any]:
    state = load_state()
    ranked = score_families(
        state
    )

    return {
        "iteration":
            state.iteration,

        "families": [
            {
                "family":
                    item.family,

                "score":
                    round(
                        item.score,
                        2,
                    ),

                "successes":
                    item.successes,

                "failures":
                    item.failures,

                "recent_failures":
                    item.recent_failures,

                "chunks_learned":
                    item.chunks_learned,

                "memory_evidence":
                    item.memory_evidence,

                "cooldown_until":
                    state.cooldown_until.get(
                        item.family,
                        0.0,
                    ),
            }
            for item in ranked
        ],
    }


__all__ = [
    "CurriculumFamily",
    "CurriculumState",
    "FAMILIES",
    "choose_next_request",
    "classify_request_family",
    "coverage_report",
    "generate_request",
    "load_state",
    "record_outcome",
    "save_state",
    "score_families",
]
